%: %.cpp
	/opt/centos/devtoolset-1.1/root/usr/bin/c++ -std=c++11 $< -o $@

laurea.o: laurea.h laurea.cpp
	g++ -c laurea.cpp -o laurea.o
corso.o: corso.h corso.cpp
	g++ -c corso.cpp -o corso.o
corsi.o: corsi.cpp
	g++ -c corsi.cpp -o corsi.o
